INSERT INTO ss_country(ID, NAME, ISO) VALUES (93, 'Австралия', '93');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (90, 'Австрия', '90');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (91, 'Австрия', '91');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (779, 'Аргентина', '779');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (54, 'Бельгия', '54');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (380, 'Болгария', '380');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (777, 'Боливия', '777');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (387, 'Босния', '387');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (789, 'Бразилия', '789');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (50, 'Великобритания', '50');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (599, 'Венгрия', '599');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (759, 'Венесуэла', '759');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (893, 'Вьетнам', '893');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (489, 'Гваделупа', '489');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (400, 'Германия', '400');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (520, 'Греция', '520');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (57, 'Дания', '57');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (746, 'Доминиканская республика', '746');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (729, 'Израиль', '729');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (890, 'Индия', '890');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (899, 'Индонезия', '899');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (539, 'Ирландия', '539');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (569, 'Исландия', '569');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (84, 'Испания', '84');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (80, 'Италия', '80');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (83, 'Италия', '83');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (9, 'Канада', '09');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (529, 'Кипр', '529');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (690, 'Китай', '690');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (691, 'Китай', '691');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (770, 'Колумбия', '770');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (740, 'Коста-Рика', '740');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (745, 'Коста-Рика', '745');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (850, 'Куба', '850');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (475, 'Латвия', '475');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (477, 'Литва', '477');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (609, 'Мавритания', '609');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (955, 'Малайзия', '955');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (535, 'Мальта', '535');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (611, 'Марокко и Западная Сахара', '611');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (750, 'Мексика', '750');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (484, 'Молдова', '484');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (87, 'Нидерландыя', '87');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (94, 'Новая Зеландия', '94');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (70, 'Норвегия', '70');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (784, 'Парагвай', '784');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (775, 'Перу', '775');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (590, 'Польша', '590');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (560, 'Португалия', '560');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (460, 'Россия', '460');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (594, 'Румыния', '594');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (860, 'Сербия', '860');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (888, 'Сингапур', '888');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (858, 'Словакия', '858');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (383, 'Словения', '383');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (0, 'Неизвестный', '00');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (1, 'США', '01');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (2, 'США', '02');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (3, 'США', '03');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (4, 'США', '04');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (5, 'США', '05');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (6, 'США', '06');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (7, 'США', '07');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (8, 'США', '08');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (885, 'Таиланд', '885');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (471, 'Тайвань', '471');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (619, 'Тунис', '619');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (869, 'Турция', '869');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (482, 'Украина', '482');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (773, 'Уругвай', '773');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (480, 'Филиппины', '480');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (64, 'Финляндия', '64');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (30, 'Франция', '30');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (31, 'Франция', '31');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (32, 'Франция', '32');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (33, 'Франция', '33');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (34, 'Франция', '34');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (35, 'Франция', '35');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (36, 'Франция', '36');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (37, 'Франция', '37');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (385, 'Хорватия', '385');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (859, 'Чехия', '859');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (780, 'Чили', '780');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (76, 'Швейцария', '76');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (73, 'Швеция', '73');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (479, 'Шри-Ланка', '479');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (786, 'Эквадор', '786');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (474, 'Эстони', '474');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (880, 'Южная Корея', '880');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (601, 'Южно-Африканская Республика', '601');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (600, 'Южно-Африканская Республика', '600');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (49, 'Япония', '49');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (487, 'Казакистан', '487');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (20, 'Резервные номера', '20');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (21, 'Резервные номера', '21');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (22, 'Резервные номера', '22');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (23, 'Резервные номера', '23');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (24, 'Резервные номера', '24');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (25, 'Резервные номера', '25');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (26, 'Резервные номера', '26');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (27, 'Резервные номера', '27');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (28, 'Резервные номера', '28');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (29, 'Резервные номера', '29');
INSERT INTO ss_country(ID, NAME, ISO) VALUES (47, 'Узбекистан', '47');
