INSERT INTO apps(ID, NAME,  CLASS_NAME, ICON, DESCRIPTION, STATE,created_date,update_date) VALUES (1, 'Администрирование',  'TAdminForm', 0, 'Администрирование', 1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO apps(ID, NAME,  CLASS_NAME, ICON, DESCRIPTION, STATE,created_date,update_date) VALUES (52, 'Инвентаризация',  'TFrmInvent', 8, 'Инвентаризация', 1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO apps(ID, NAME,  CLASS_NAME, ICON, DESCRIPTION, STATE,created_date,update_date) VALUES (60, 'Отчеты',  'TFrmReporst', 9, 'Отчеты', 1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO apps(ID, NAME,  CLASS_NAME, ICON, DESCRIPTION, STATE,created_date,update_date) VALUES (45, 'Банкеты',  'TFrmBanket', 26, 'Банкеты', 1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO apps(ID, NAME,  CLASS_NAME, ICON, DESCRIPTION, STATE,created_date,update_date) VALUES (62, 'Мониторинг',  'TFrmGraf_01', 11, 'Мониторинг', 1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO apps(ID, NAME,  CLASS_NAME, ICON, DESCRIPTION, STATE,created_date,update_date) VALUES (40, 'Расходы',  'TFrmChecks', 6, 'Расходы', 1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO apps(ID, NAME,  CLASS_NAME, ICON, DESCRIPTION, STATE,created_date,update_date) VALUES (-1, 'Глобальные константы',  'xxxx', 0, 'Глобальные константы', 99,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO apps(ID, NAME,  CLASS_NAME, ICON, DESCRIPTION, STATE,created_date,update_date) VALUES (10, 'Продавец',  'TFrmCeller', 1, 'Продавец', 1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO apps(ID, NAME,  CLASS_NAME, ICON, DESCRIPTION, STATE,created_date,update_date) VALUES (30, 'Меню',  'TFrmGoods', 24, 'Меню', 1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO apps(ID, NAME,  CLASS_NAME, ICON, DESCRIPTION, STATE,created_date,update_date) VALUES (90, 'VIP клиенты (Дисконт)',  'TFrmDiscount', 15, 'VIP клиенты (Дисконт)', 1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO apps(ID, NAME,  CLASS_NAME, ICON, DESCRIPTION, STATE,created_date,update_date) VALUES (22, 'Приход товаров',  'TFrmInput', 3, 'Приход', 1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO apps(ID, NAME,  CLASS_NAME, ICON, DESCRIPTION, STATE,created_date,update_date) VALUES (24, 'Возврат и списание',  'TFrmInOut', 19, 'Возврат и списание', 1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO apps(ID, NAME,  CLASS_NAME, ICON, DESCRIPTION, STATE,created_date,update_date) VALUES (25, 'Список приходов',  'TFrmAllInputs', 4, 'Список приходов', 1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO apps(ID, NAME,  CLASS_NAME, ICON, DESCRIPTION, STATE,created_date,update_date) VALUES (51, 'Терминал',  'TFrmTerminal', 22, 'Терминал', 1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO apps(ID, NAME,  CLASS_NAME, ICON, DESCRIPTION, STATE,created_date,update_date) VALUES (46, 'Поставщики',  'TFrmVendors', 33, 'Поставщики', 1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO apps(ID, NAME,  CLASS_NAME, ICON, DESCRIPTION, STATE,created_date,update_date) VALUES (26, 'Ингридиенты',  'TFrmSostav', 34, 'Ингридиенты', 1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO apps(ID, NAME,  CLASS_NAME, ICON, DESCRIPTION, STATE,created_date,update_date) VALUES (47, 'Клиенты',  'TFrmClients', 35, 'Клиенты', 0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO apps(ID, NAME,  CLASS_NAME, ICON, DESCRIPTION, STATE,created_date,update_date) VALUES (100, 'Расход со склада',  'TFrmOuts', 1, 'Расход со склада', 0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
