INSERT INTO SS_UNIT(ID, NAME, STATUS, ORDERBY) VALUES (2, 'шт', 1, 2);
INSERT INTO SS_UNIT(ID, NAME, STATUS, ORDERBY) VALUES (3, 'порция', 1, 4);
INSERT INTO SS_UNIT(ID, NAME, STATUS, ORDERBY) VALUES (4, 'кг', 2, 1);
INSERT INTO SS_UNIT(ID, NAME, STATUS, ORDERBY) VALUES (5, 'грамм', 2, 5);
INSERT INTO SS_UNIT(ID, NAME, STATUS, ORDERBY) VALUES (6, 'литр', 2, 3);
INSERT INTO SS_UNIT(ID, NAME, STATUS, ORDERBY) VALUES (7, 'метр', 2, 6);
INSERT INTO SS_UNIT(ID, NAME, STATUS, ORDERBY) VALUES (8, 'минут', 2, 7);
