INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (62, '1', 'Форма чека', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (63, '1', 'Автопечать', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (35, 'СПАСИБО ЗА ПОКУПКУ!!!', 'Заставка для дисплея покупателя №1', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (36, 'СПАСИБО ЗА ПОКУПКУ!!!', 'Заставка для дисплея покупателя №2', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (621, '1', '<<В долг>> Старшему кассиру разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (30, 'АВТОМАТИЗАЦИЯ ПОИЗВОДСТВА', 'Заголовок программы', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (39, '0', 'Округление', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (44, '0', 'Положение десяточной точки', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (64, '2', 'Cмены', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (45, 'сум', 'Денежная единица', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (46, 'тийин', 'Денежная единица', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (14, '1%%%%', 'Маска идентификатора', 0);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (4, 'LAGMAN HOUSE', 'Наименование для чека', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (100, 'Харидорнинг пули етмади', 'Причина для отмены чека ', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (101, 'Харидор кайтариб келди', 'Причина для отмены чека', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (102, 'Кассир адашган', 'Причина для отмены чека', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (200, 'Сроги утган', 'Причина для списания', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (201, 'Сотиш учун яроксиз', 'Причина для списания', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (20, '0', 'Граница удаления чеков в днях', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (8, '10000000', 'Максимальная разрешенная сумма', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (0, 'Oshxona', 'Наименование организации', 0);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (50, '1', 'Максимальное количество чеков для одного стола', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (51, '1', 'Кассиру разрешается отменить заказ', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (52, '0', 'Официанту разрешается отменить', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (59, '1', 'Официанту разрешается отправить заказ', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (60, '1', 'Кассиру разрешается отправить заказ', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (65, '1', 'Объязательная отправка заказа', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (611, '0', '<<Отменить состояние "Распечатан предварительный чек">> Официанту разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (511, '0', '<<Обединить>> Официанту разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (512, '1', '<<Обединить>> Старшему к разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (513, '0', '<<Обединить>> Кассиру разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (514, '0', '<<Обединить>> Оператору разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (521, '0', '<<Изменить номер стола и офицанта>> Официанту разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (522, '1', '<<Изменить номер стола и офицанта>> Старшему кассиру разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (523, '0', '<<Изменить номер стола и офицанта>> Кассиру разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (524, '0', '<<Изменить номер стола и офицанта>> Оператору разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (531, '0', '<<Утверждение смену кассира>> Официанту разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (532, '1', '<<Утверждение смену кассира>> Старшему кассиру разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (533, '0', '<<Утверждение смену кассира>> Кассиру разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (534, '0', '<<Утверждение смену кассира>> Оператору разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (541, '0', '<<Менять % услуги>> Официанту разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (542, '1', '<<Менять % услуги>> Старшему кассиру разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (543, '0', '<<Менять % услуги>> Кассиру разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (544, '0', '<<Менять % услуги>> Оператору разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (551, '1', '<<Печать текущий заказ F8>> Официанту разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (552, '1', '<<Печать текущий заказ F8>> Старшему кассиру разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (622, '1', '<<В долг>> Кассиру разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (553, '1', '<<Печать текущий заказ F8>> Кассиру разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (554, '1', '<<Печать текущий заказ F8>> Оператору разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (561, '1', '<<Печать заказы F9>> Официанту разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (562, '1', '<<Печать заказы F9>> Старшему кассиру разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (563, '1', '<<Печать заказы F9>> Кассиру разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (564, '1', '<<Печать заказы F9>> Оператору разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (571, '1', '<<Печать чек F10>> Официанту разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (572, '1', '<<Печать чек F10>> Старшему кассиру разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (573, '1', '<<Печать чек F10>> Кассиру разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (574, '1', '<<Печать чек F10>> Оператору разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (581, '0', '<<Удалить заказ Del>> Официанту разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (582, '1', '<<Удалить заказ Del>> Старшему кассиру разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (583, '1', '<<Удалить заказ Del>> Кассиру разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (584, '0', '<<Удалить заказ Del>> Оператору разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (591, '0', '<<Стоп лист Ctrl+S>> Официанту разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (592, '1', '<<Стоп лист Ctrl+S>> Старшему кассиру разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (593, '1', '<<Стоп лист Ctrl+S>> Кассиру разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (594, '1', '<<Стоп лист Ctrl+S>> Оператору  кассиру разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (601, '0', '<<Дисконтная карта F5>> Официанту разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (602, '1', '<<Дисконтная карта F5>> Старшему кассиру разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (603, '0', '<<Дисконтная карта F5>> Кассиру разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (604, '0', '<<Дисконтная карта F5>> Оператору разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (66, '6', 'Ключевой порядковый номер для чека', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (612, '1', '<<Отменить состояние "Распечатан предварительный чек">> Старшему кассиру разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (613, '1', '<<Отменить состояние "Распечатан предварительный чек">> Кассиру разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (614, '1', '<<Отменить состояние "Распечатан предварительный чек">> Оператору разрешается', 1);
INSERT INTO ss_settings(ID, MY_VALUE, NAME, IS_ENABLED) VALUES (500, '0', 'Кассиру разрешается добавить блюд в заказ официантов', 1);
